### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by 842Mono** [CPJKU/dcase_task2#6]
When I try running this command:

    python3 prepare_spectrograms.py --audio_path <DATA_ROOT>/audio_train --spec_version 1 --show 10

I get this error:

```
Traceback (most recent call last):
  File "prepare_spectrograms.py", line 94, in <module>
    if not os.path.exists(args.spec_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by stefan-balke** [comment]
The repo is written in Python 2.7. Maybe we should add it to the Readme.
